# np.pad
- ‘constant’——表示连续填充相同的值，每个轴可以分别指定填充值，constant_values=（x, y）时前面用x填充，后面用y填充，缺省值填充0
- ‘edge’——表示用边缘值填充
- ‘linear_ramp’——表示用边缘递减的方式填充
- ‘maximum’——表示最大值填充
- ‘mean’——表示均值填充
- ‘median’——表示中位数填充
- ‘minimum’——表示最小值填充
- ‘reflect’——表示对称填充
- ‘symmetric’——表示对称填充
- ‘wrap’——表示用原数组后面的值填充前面，前面的值填充后面

In [3]:
import numpy as np
A = np.arange(95,99).reshape(2,2)
print(A)

[[95 96]
 [97 98]]


In [26]:
# np.pad(<input>,<列上下填充(上,下)>,<行左右填充(左,右)>,<'constant'>,<填充值(上左,下右)>)
# constant_values 先上下在左右填入
B = np.pad(A,((1,1),(1,1)),'constant',constant_values = (1,2))
print(B)

[[ 1  1  1  2]
 [ 1 95 96  2]
 [ 1 97 98  2]
 [ 1  2  2  2]]


In [32]:
# np.pad(<input>,<列上下填充(上,下)>,<行左右填充(左,右)>,<'edge'>)
C = np.pad(A,((2,2),(2,2)),'edge')
print(C)

[[95 95 95 96 96 96]
 [95 95 95 96 96 96]
 [95 95 95 96 96 96]
 [97 97 97 98 98 98]
 [97 97 97 98 98 98]
 [97 97 97 98 98 98]]


In [37]:
D = np.pad(B,(1, 2),'linear_ramp',end_values=(1,2))
print(D)

[[ 1  1  1  1  1  1  2]
 [ 1  1  1  1  2  2  2]
 [ 1  1 95 96  2  2  2]
 [ 1  1 97 98  2  2  2]
 [ 1  1  2  2  2  2  2]
 [ 1  1  2  2  2  2  2]
 [ 1  2  2  2  2  2  2]]


In [8]:
E = np.pad(A,((3,2),(2,3)),'maximum')
print(E)

[[98 98 97 98 98 98 98]
 [98 98 97 98 98 98 98]
 [98 98 97 98 98 98 98]
 [96 96 95 96 96 96 96]
 [98 98 97 98 98 98 98]
 [98 98 97 98 98 98 98]
 [98 98 97 98 98 98 98]]
