In [1]:
import cv2
import numpy as np
import math
from PIL import Image 

In [2]:
def Negative(imageGray):
    H,W = imageGray.shape
    L = np.ones([H,W])*256
    image = np.uint8((L - 1) - imageGray)
    return image

In [ ]:
image = cv2.imread("/Users/yeshiouwei/Desktop/OpenCV/Image/Lenna.jpg")
imageGray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
print(imageGray)
print("=========================================")
imageTh = (Negative(imageGray))
print(imageTh)
htich = np.hstack((imageTh, imageGray))
cv2.imshow("image",htich)
#cv2.imshow("image2",imageGray)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[162 162 162 ... 171 167 142]
 [162 162 162 ... 171 167 142]
 [162 162 162 ... 171 166 142]
 ...
 [ 51  49  51 ...  93  97  94]
 [ 44  47  51 ...  99 102 101]
 [ 44  51  53 ... 103 104 107]]
[[ 93  93  93 ...  84  88 113]
 [ 93  93  93 ...  84  88 113]
 [ 93  93  93 ...  84  89 113]
 ...
 [204 206 204 ... 162 158 161]
 [211 208 204 ... 156 153 154]
 [211 204 202 ... 152 151 148]]
