In [1]:
import cv2
import numpy as np
import math

In [2]:
def Power_law(imageGray):
    H,W = imageGray.shape
    r = 0.3
    c = 100
    imagePo = np.uint8(imageGray**r)*c
    return imagePo

In [3]:
image = cv2.imread("/Users/yeshiouwei/Desktop/OpenCV/Image/Lenna.jpg")
imageGray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
imagePo = Power_law(imageGray)
print(imageGray)
print("=========================================")
print(imagePo)
htich = np.hstack((imagePo, imageGray))
cv2.imshow("image",htich)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[162 162 162 ... 171 167 142]
 [162 162 162 ... 171 167 142]
 [162 162 162 ... 171 166 142]
 ...
 [ 51  49  51 ...  93  97  94]
 [ 44  47  51 ...  99 102 101]
 [ 44  51  53 ... 103 104 107]]
[[144 144 144 ... 144 144 144]
 [144 144 144 ... 144 144 144]
 [144 144 144 ... 144 144 144]
 ...
 [ 44  44  44 ...  44  44  44]
 [ 44  44  44 ...  44 144  44]
 [ 44  44  44 ... 144 144 144]]
